function save(a){Config.set(a,function(){simpleErrorHandler(tl("error_settings_save"))||on&&startPreview()})}function reset(){Config.clear(function(){simpleErrorHandler(tl("error_settings_reset"));removeEffect();location.reload(!0)})}function applyToAllTabs(a){chrome.tabs.query({url:"http://*/*"},a);chrome.tabs.query({url:"https://*/*"},a)}function startPreview(){applyToAllTabs(function(a){for(var c=0,b=a.length;c<b;++c)chrome.tabs.executeScript(a[c].id,{file:"/js/preview.js",allFrames:!0})})}
function removeEffect(){applyToAllTabs(function(a){for(var c=0,b=a.length;c<b;++c)chrome.tabs.executeScript(a[c].id,{code:'var css = document.getElementById("Force_Custom_Fonts");css && css.remove();',allFrames:!0})})}
function fixFontRange(a){a=a.replace(/[^0-9A-F,\-]/gi,"").replace(/([\-,]){2,}/g,"$1").replace(/,-[^,]+|[^,]+-,/g,"").split(",");a=a.filter(function(a){if(/-/.test(a)){var b;a=a.split("-");b=parseInt(a[0],16);a=parseInt(a[1],16);if(b<=a&&0<=b&&1114111>=a)return!0}else if(a=parseInt(a,16),0<a&&1114111>a)return!0;return!1});return a.join(",")}
function bindEvents(){btn_switch.addEventListener("click",function(){on=!on;LocalConfig.set({off:!on},function(){simpleErrorHandler(tl("error_settings_save"))||(btn_switch.className=on?"on":"off",on?startPreview():removeEffect())})},!1);btn_reset.addEventListener("click",reset,!1);btn_save.addEventListener("click",function(){for(var a={"font-cjk":select_cjk.value.trim(),"font-latin":select_latin.value.trim(),"font-fixed":select_fixed.value.trim(),"font-other":select_other.value.trim(),transformations:{}},
c=$$(".font-trans:not([id])",trans_form),b=0,h=c.length,d,f,k,e={};b<h;)d=c[b],f=$(".font-from",d).value,k=$(".font-to",d).value,d=fixFontRange($(".font-range",d).value),f&&k&&(e[f]=e[f]||[],e[f].push([k,d])),++b;a.transformations=e;save(a)},!1);btn_pause.addEventListener("click",function(){removeEffect()},!1);trans_add.addEventListener("click",function(){var a=trans_temp.cloneNode(!0);$(".trans-del",a).addEventListener("click",function(){a.remove()},!1);a.removeAttribute("id");a.removeAttribute("style");
trans_form.appendChild(a)},!1)}
function init(a,c){data_list=$("#font-list");btn_switch=$("#switch");btn_save=$("#save");btn_reset=$("#reset");btn_pause=$("#pause");trans_add=$("#trans-add");g=$("#trans-del");select_cjk=$("#font-cjk");select_latin=$("#font-latin");select_fixed=$("#font-fixed");select_other=$("#font-other");trans_form=$("#trans-form");trans_temp=$("#trans-temp");bindEvents();LocalConfig.get({off:!1},function(a){simpleErrorHandler(tl("error_settings_load"))||(btn_switch.className=a.off?"off":"on",on=!a.off)});var b,
h,d=$$$("option",{innerText:tl("settings_font_default")},{value:""});font_list.appendChild(d);for(var f=0,k=c.length;f<k;++f)b=c[f].displayName,h=c[f].fontId,g=d.cloneNode(),g.value=h,g.innerText=b,font_list.appendChild(g);[data_list,select_cjk,select_latin,select_fixed,select_other].forEach(function(a){a.appendChild(font_list.cloneNode(!0))});select_cjk.value=a["font-cjk"];select_latin.value=a["font-latin"];select_fixed.value=a["font-fixed"];select_other.value=a["font-other"];b=a.transformations;
var e,g,l;for(l in b)for(h=b[l]||[],f=0;d=h[f];++f)g=d[0],d=d[1],l&&g&&(e=trans_temp.cloneNode(!0),e.removeAttribute("id"),e.removeAttribute("style"),$(".font-from",e).value=l,$(".font-to",e).value=g,$(".font-range",e).value=d,g=$(".trans-del",e),g.addEventListener("click",function(){e.remove()},!1),trans_form.appendChild(e))}
var font_list=document.createDocumentFragment(),data_list,on,btn_switch,btn_save,btn_reset,btn_pause,trans_add,trans_del,select_cjk,select_latin,select_fixed,select_other,trans_form,trans_temp;window.addEventListener("load",function(){Config.get({"font-cjk":"","font-latin":"","font-fixed":"","font-other":"",transformations:{}},function(a){simpleErrorHandler(tl("error_settings_load"))||chrome.fontSettings.getFontList(function(c){init(a,c)})})},!1);
